name: Checkout PR Head
description: "Checkout the head of a pull request"
inputs:
  pr_number:
    description: "PR number"
    required: true
  gh_token:
    description: "GitHub token"
    required: true
    default: ${{ secrets.GITHUB_TOKEN }}
  gh_repo:
    description: "GitHub repository"
    required: true
    default: ${{ github.repository }}

runs:
  using: "composite"
  steps:
    - name: Get PR head commit SHA
      id: pr_head_sha
      shell: bash
      run: gh pr view ${{ inputs.pr_number }} --json headRefOid -q '.headRefOid'
      env:
        GH_REPO: ${{ inputs.gh_repo }}
        GH_TOKEN: ${{ inputs.gh_token }}

    - name: Checkout PR head
      uses: actions/checkout@v4
      with:
        ref: ${{ steps.pr_head_sha.outputs.stdout }}
        repository: ${{ inputs.gh_repo }}
        token: ${{ inputs.gh_token }}
