name: ESLint
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
concurrency:
  group: ${{ github.workflow_ref }}-${{ github.event.number || github.sha }}
  cancel-in-progress: true
permissions: {}
jobs:
  eslint:
    name: ESLint
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          persist-credentials: false
      - name: Install Nix
        uses: DeterminateSystems/determinate-nix-action@131015bad844610e5e6300f8a143bf625d3e74f4 # v3.17.0
      - name: Install dependencies
        run: nix develop --command bun install --frozen-lockfile
      - name: Run ESLint
        run: nix develop --command bun run lint
