name: Nix flake check
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths:
      - "**/*.nix"
      - "**/flake.lock"
concurrency:
  group: ${{ github.workflow_ref }}-${{ github.event.number || github.sha }}
  cancel-in-progress: true
permissions: {}
jobs:
  flake-check:
    uses: cffnpwr/actions/.github/workflows/flake-check.yaml@d09e1234a71be2ff954d851d1ead90a60e17bcfb
    permissions:
      contents: read
