name: Nix flake check
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths:
      - "**/*.nix"
      - "**/flake.lock"
concurrency:
  group: ${{ github.workflow_ref }}-${{ github.event.number || github.sha }}
  cancel-in-progress: true
permissions: {}
jobs:
  flake-check:
    uses: cffnpwr/actions/.github/workflows/flake-check.yaml@827d6803313793c29f98826d5d9c00e92da976cb
    permissions:
      contents: read
