name: Publish
on:
  release:
    types:
      - published
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
permissions: {}
jobs:
  publish-npm:
    name: Publish to npm
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
        with:
          persist-credentials: false
      - name: Install Nix
        uses: DeterminateSystems/determinate-nix-action@131015bad844610e5e6300f8a143bf625d3e74f4 # v3.17.0
      - name: Install dependencies
        run: nix develop .#publish --command bun install --frozen-lockfile
      - name: Build
        run: nix develop .#publish --command bun run build
      - name: Publish to npm
        run: nix develop .#publish --command bunx pnpm publish --provenance --access public --no-git-checks
  publish-jsr:
    name: Publish to JSR
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
        with:
          persist-credentials: false
      - name: Install Nix
        uses: DeterminateSystems/determinate-nix-action@131015bad844610e5e6300f8a143bf625d3e74f4 # v3.17.0
      - name: Install dependencies
        run: nix develop .#publish --command bun install --frozen-lockfile
      - name: Publish to JSR
        run: nix develop .#publish --command bun run publish:jsr
