name: Publish
on:
  release:
    types:
      - published
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
permissions: {}
jobs:
  publish-npm:
    name: Publish to npm
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - name: Install Nix
        uses: DeterminateSystems/determinate-nix-action@131015bad844610e5e6300f8a143bf625d3e74f4 # v3.17.0
      - name: Setup Node.js
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: "24.x"
          registry-url: "https://registry.npmjs.org"
      - name: Install dependencies
        run: nix develop .#publish --command bun install --frozen-lockfile
      - name: Build
        run: nix develop .#publish --command bun run build
      - name: Publish to npm
        run: nix develop .#publish --command bunx pnpm publish --provenance --access public --no-git-checks
  publish-jsr:
    name: Publish to JSR
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - name: Install Nix
        uses: DeterminateSystems/determinate-nix-action@131015bad844610e5e6300f8a143bf625d3e74f4 # v3.17.0
      - name: Install dependencies
        run: nix develop .#publish --command bun install --frozen-lockfile
      - name: Publish to JSR
        run: nix develop .#publish --command bun run publish:jsr
