name: Release
on:
  pull_request_target:
    branches:
      - release
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited

jobs:
  fetch_label:
    runs-on: ubuntu-latest
    outputs:
      release_level: ${{ steps.check_labels.outputs.release_level }}
    steps:
      - name: Checkout
        uses: ./.github/actions/checkout
        with:
          pr_number: ${{ github.event.pull_request.number }}

      - name: Fetch labels
        id: labels
        env:
          GH_REPO: ${{ github.repository }}
          GH_TOKEN: ${{ github.token }}
        run: |
          json=$(gh pr view ${{ github.event.pull_request.number }} --json labels -q '.labels | map(.name)')
          echo "json=$json" >> "$GITHUB_OUTPUT"

      - name: Check labels
        uses: actions/github-script@v6
        env:
          LABELS: ${{ steps.labels.outputs.json }}
        with:
          script: |
            const { LABELS } = process.env;
            const labels = JSON.parse(LABELS);
            const releaseLabels = labels.filter((label) => label.startsWith("release/"));
            if (releaseLabels.length == 0) {
              core.setFailed('No release label found');
              process.exit(1);
            }

            let releaseLevel;
            if (releaseLabels.includes("release/major")) {
              releaseLevel = "major";
            } else if (releaseLabels.includes("release/minor")) {
              releaseLevel = "minor";
            } else if (releaseLabels.includes("release/patch")) {
              releaseLevel = "patch";
            } else {
              core.setFailed('No release level found');
              process.exit(1);
            }

            core.setOutput('release_level', releaseLevel)
          result-encoding: string

  runtime_test:
    needs:
      - fetch_label
    uses: ./.github/workflows/runtime_test.yaml
    with:
      pr_number: ${{ github.event.pull_request.number }}

  update_version:
    needs:
      - fetch_label
      - runtime_test
    runs-on: ubuntu-latest
    outputs:
      new_version: ${{ steps.get_new_version.outputs.new_version }}
    steps:
      - name: Checkout
        uses: ./.github/actions/checkout
        with:
          pr_number: ${{ github.event.pull_request.number }}

      - name: Get previous version
        id: get_prev_version
        env:
          GH_REPO: ${{ github.repository }}
          GH_TOKEN: ${{ github.token }}
        run: |
          version=$(gh release view --json tagName -q '.tagName' || echo "0.0.0")
          echo "prev_version=$version" >> "$GITHUB_OUTPUT"

      - name: Get current version from deno.json
        id: get_current_version
        run: |
          version=$(cat deno.json | jq -r '.version')
          echo "current_version=$version" >> "$GITHUB_OUTPUT"

      - name: Setup Deno
        if: steps.get_current_version.outputs.current_version == steps.get_prev_version.outputs.prev_version
        uses: denoland/setup-deno@v2
        with:
          deno-version: "2.x"

      - name: Install Dependencies
        if: steps.get_current_version.outputs.current_version == steps.get_prev_version.outputs.prev_version
        run: deno install

      - name: update version
        if: steps.get_current_version.outputs.current_version == steps.get_prev_version.outputs.prev_version
        run: deno task update-version ${{ needs.fetch_label.outputs.release_level }}

      - name: Set git user
        if: steps.get_current_version.outputs.current_version == steps.get_prev_version.outputs.prev_version
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Commit changes
        if: steps.get_current_version.outputs.current_version == steps.get_prev_version.outputs.prev_version
        run: |
          if ! git diff --exit-code --quiet; then
            git add .
            git commit -m "chore: bump version"
            git push origin ${{ github.event.pull_request.head.ref }}
          fi

      - name: Get new version
        id: get_new_version
        run: |
          version=$(cat deno.json | jq -r '.version')
          echo "new_version=$version" >> "$GITHUB_OUTPUT"

  merge_pr:
    needs:
      - update_version
    runs-on: ubuntu-latest
    steps:
      - name: Merge PR
        env:
          GH_TOKEN: ${{ github.token }}
          GH_REPO: ${{ github.repository }}
        run: gh pr merge ${{ github.event.pull_request.number }} --auto --squash

      - name: Delete branch
        run: git push origin --delete ${{ github.event.pull_request.head.ref }}

  create_release:
    needs:
      - update_version
      - merge_pr
    runs-on: ubuntu-latest
    steps:
      - name: Create release
        env:
          GH_TOKEN: ${{ github.token }}
          GH_REPO: ${{ github.repository }}
          NEW_VERSION: ${{ needs.update_version.outputs.new_version }}
        run: |
          gh release create ${{ env.NEW_VERSION }} --title "Release ${{ env.NEW_VERSION }}" --generate-notes --target release

