name: Runtime Test
on:
  pull_request:
    branches:
      - main
    paths:
      - "**/*.ts"
      - "**/package.json"
      - "**/bun.lock"
      - "**/tsconfig.json"
  workflow_call:
concurrency:
  group: ${{ github.workflow_ref }}-${{ github.event.number }}
  cancel-in-progress: true
permissions: {}
jobs:
  runtime_test:
    name: Runtime Test
    runs-on: ubuntu-24.04
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - name: Install Nix
        uses: DeterminateSystems/determinate-nix-action@92ffb5400c3776307a27a1727d7e2ac3dcd9f844 # v3.18.1
      - name: Install dependencies
        run: nix develop .#runtime-test --command bun install --frozen-lockfile
      - name: Build package
        run: nix develop .#runtime-test --command bun run build-package
      - name: Runtime Test (node)
        run: nix develop .#runtime-test --command bun run runtime-test node
      - name: Runtime Test (bun)
        run: nix develop .#runtime-test --command bun run runtime-test bun
      - name: Runtime Test (deno)
        run: nix develop .#runtime-test --command bun run runtime-test deno
