name: Runtime Test
on:
  pull_request_target:
    branches:
      - main
      - release
  workflow_call:
    inputs:
      pr_number:
        type: number
        description: "Pull Request Number"
        required: true
        default: ${{ github.event.pull_request.number }}

jobs:
  runtime_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        runtime:
          - node
          - bun
          - deno
    steps:
      - name: Checkout
        uses: ./.github/actions/checkout
        with:
          pr_number: ${{ github.event_name == 'workflow_call' && github.event.inputs.pr_number || github.event.pull_request.number }}

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: "2.x"

      - name: Setup Node
        if: matrix.runtime == 'node'
        uses: actions/setup-node@v2
        with:
          node-version: "22.x"

      - name: Setup Bun
        if: matrix.runtime == 'bun'
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: "1.x"

      - name: Install Dependencies
        run: deno install

      - name: Run Tests
        run: deno task runtime-test ${{ matrix.runtime }}
