name: Runtime Test
on:
  pull_request:
    branches:
      - main
    paths:
      - "**/*.ts"
      - "**/package.json"
      - "**/bun.lock"
      - "**/tsconfig.json"
  workflow_call:
concurrency:
  group: ${{ github.workflow_ref }}-${{ github.event.number }}
  cancel-in-progress: true
permissions: {}
jobs:
  runtime_test:
    name: Runtime Test
    runs-on: ubuntu-24.04
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false
      - name: Install Nix
        uses: DeterminateSystems/determinate-nix-action@629b284231c2a82554b724e357e47fc6020833c8 # v3.21.2
      - name: Install dependencies
        run: nix develop .#runtime-test --command bun install --frozen-lockfile
      - name: Build package
        run: nix develop .#runtime-test --command bun run build-package
      - name: Runtime Test (node)
        run: nix develop .#runtime-test --command bun run runtime-test node
      - name: Runtime Test (bun)
        run: nix develop .#runtime-test --command bun run runtime-test bun
      - name: Runtime Test (deno)
        run: nix develop .#runtime-test --command bun run runtime-test deno
