name: Semantic PR title
on:
  pull_request_target: # zizmor: ignore[dangerous-triggers]
    branches:
      - main
    types:
      - opened
      - edited
      - reopened
      - synchronize
concurrency:
  group: ${{ github.workflow_ref }}-${{ github.event.number }}
  cancel-in-progress: true
permissions: {}
jobs:
  semantic-pr-title:
    uses: cffnpwr/actions/.github/workflows/semantic-pr-title.yaml@ab13c0cd1ecb5c1c0486c3df64a999e8a0841431 # main
    permissions:
      pull-requests: read
