name: treefmt check
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
concurrency:
  group: ${{ github.workflow_ref }}-${{ github.event.number || github.sha }}
  cancel-in-progress: true
permissions: {}
jobs:
  treefmt:
    name: Run treefmt
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Setup mise
        uses: jdx/mise-action@9149ea85001c7435d5a66bb127d6a1b6227cb0a5 # v5.0.0
      - name: Run treefmt
        run: treefmt --fail-on-change
