name: treefmt check
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
concurrency:
  group: ${{ github.workflow_ref }}-${{ github.event.number || github.sha }}
  cancel-in-progress: true
permissions: {}
jobs:
  treefmt:
    name: Run treefmt
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Install Nix
        uses: DeterminateSystems/determinate-nix-action@2a0be2498974c2b6327e19780488744384637d88 # v3.21.7
      - name: Run treefmt
        run: nix develop --command treefmt --fail-on-change
